name: flutter_i18n
description: i18n made easy for Flutter
version: 0.0.1
author: Matteo Pietro Dazzi <matteopietro.dazzi@gmail.com>
homepage: https://github.com/ilteoood/flutter_i18n

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=1.19.0 <2.0.0"