name: flutter_i18n
description: i18n made easy for Flutter
version: 0.0.1
author:
homepage:

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter